create table cust_org(
	tech_change_time text,
	tech_session_id text default pg_backend_pid(), 
	client_id text,
	name text,
	short_name text,
	eng_name text,
	okopf_code text, 
	okopf_name text, 
	okfc_code text, 
	okfc_name text,
	type_of_activity text,
	country_name text,
	inn text,
	inn_hist text default '[]', 
	kio text,
	kio_hist text default '[]',
	kpp_main text, 
	kpp_main_hist text default '[]', 
	ogrn text, 
	ogrn_hist text default '[]', 
	registration_date text,
	registration_doc text,
	registration_authority_name text, 
	fns_registration_date text,
	fns_registration_doc text, 
	okato_code text,
	okato_name text,
	list_okved_code text default '[]',
	list_okved_name text default '[]',
	authorized_capital_amt text,
	list_legal_address text default '[]',
	list_fact_address text default '[]',
	list_phone text default '[]',
	list_fax text default '[]',
	list_email text default '[]',
	swift text,
	is_currency_residence text,
	is_tax_resident text,
	director_name text,
	chief_accountant_name text,
	business_segment_name text,
	bankruptcy_info text,
	elimination_info text,
	service_start_date text,
	bic text,
	reg_num text,
	corr_acc_num text,
	list_natural_client_id text default '[]' 	
)
distributed by (client_id);
